name: Continous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node }}


    - name: Install packages
      run: yarn

    - name: Execute tests
      run: yarn test

  ember-cli-update:
    needs: test
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
    - uses: kellyselden/ember-cli-update-action@master
      with:
        autofix_command: npm run lint -- --fix
