name: Continous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node }}

    - name: Install packages
      run: npm install

    - name: Execute tests
      run: npm test

    - name: Coverage test
      run: COVERAGE=TRUE npm run test:ember

    - uses: actions/upload-artifact@v1
      with:
        name: pr_coverage_summary_json
        path: coverage/coverage-summary.json

  simple-coverage-report:
    name: Code coverage changes
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@v1
      with:
        name: pr_coverage_summary_json
    - shell: bash 
      id: coverage_result
      run: echo ::set-output name=COVERAGE_RESULT::$(cat pr_coverage_summary_json/coverage-summary.json)

    - uses: abhilashlr/simple-coverage-report@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        artifact-json: ${{ steps.coverage_result.outputs.COVERAGE_RESULT }}

  ember-cli-update:
    name: CLI update
    needs: test
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
    - uses: kellyselden/ember-cli-update-action@master
      with:
        autofix_command: npm run lint -- --fix
