name: Continous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node }}

    - name: Install packages
      run: npm install

    - name: Execute tests
      run: npm test

  simple-coverage-report:
    needs: test
    runs-on: ubuntu-latest
    name: Code coverage changes

    - uses: abhilashlr/simple-coverage-report@89e988d092b1f8d1d9299371aedbfc038a88ebda
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  ember-cli-update:
    needs: test
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
    - uses: kellyselden/ember-cli-update-action@master
      with:
        autofix_command: npm run lint -- --fix
